name: Appium Mobile Tests

on:
  push:
    branches:
      - main

jobs:
  appium-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Check Android Device
        run: adb devices

      - name: Start Appium Server
        shell: powershell
        run: |
          Start-Process appium `
            -ArgumentList "--address 127.0.0.1 --port 4725" `
            -WindowStyle Hidden

          Start-Sleep -Seconds 5

      - name: Run Appium Test
        run: mvn -Dtest=HomeTest#testSearch test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: appium-test-results
          path: target/surefire-reports/